const assert = require('assert')
const fs = require('fs')
const os = require('os')
const path = require('path')
const { execFileSync, spawnSync } = require('child_process')
const kb = require('../lib/kb-maintenance.cjs')
const cli = require('../commands/kb-maintenance.js')
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'fsflow-kb-maintenance-'))
const put = (f, text) => { fs.mkdirSync(path.dirname(path.join(root, f)), { recursive: true }); fs.writeFileSync(path.join(root, f), text) }
const git = (...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim()
const record = scope => kb.record(root, { scope, status: 'updated', reason: 'Reviewed implementation and specifications', specReview: 'aligned' })
let total = 0
function test (name, fn) { fn(); total++; console.log('✓ ' + name) }
try {
  git('init', '-q'); git('config', 'user.name', 'KB Test'); git('config', 'user.email', 'kb@example.invalid')
  git('config', 'core.hooksPath', path.join(root, '.git/hooks'))
  put('src/order.js', 'export const cancelMinutes = 30\n')
  put('src/user.js', 'export const enabled = true\n')
  put('.docs/llm-knowledge/meta.yaml', 'git:\n  hash: ""\ndomains:\n  - id: order\n    path: business/order/\n    entry_files: [src/order.js]\n  - id: user\n    path: business/user/\n    entry_files: [src/user.js]\n')
  put('.docs/llm-knowledge/business/order/overview.md', '# Order\nCancel within 30 minutes.\n')
  put('.docs/llm-knowledge/business/user/overview.md', '# User\nEnabled.\n')
  put('.docs/llm-knowledge/overview.md', '# Project\n[Order](business/order/overview.md)\n')
  test('Portable install preserves a fixed same-repository root', () => {
    const r = cli.install(root, true)
    assert(r.hooksInstalled)
    assert(fs.existsSync(path.join(root, r.installed, 'lib/kb-maintenance.cjs')))
    assert.equal(JSON.parse(fs.readFileSync(path.join(root, r.installed, 'package.json'), 'utf8')).type, 'commonjs')
    assert(!fs.existsSync(path.join(root, '.docs/llm-knowledge/master')))
  })
  test('Checks do not certify unreviewed scopes or write receipts', () => {
    const r = kb.check(root, { strict: true })
    assert(!r.passed); assert(r.pending.some(p => p.scope === 'domain:order'))
    assert(!fs.existsSync(path.join(root, '.docs/llm-knowledge/maintenance')))
  })
  record('domain:order'); record('domain:user'); record('common')
  test('Reviewed baseline passes in working tree and staged snapshot', () => {
    assert(kb.check(root, { strict: true }).passed)
    git('add', '.')
    assert(kb.check(root, { mode: 'staged', strict: true }).passed)
    git('commit', '-qm', 'baseline')
  })
  const base = git('rev-parse', 'HEAD')
  test('Receipts replace the legacy empty global hash in update/freshness plans', () => {
    const plan = require('../../skills/kb-update/kb-update.cjs').collectUpdate(root, { refresh: false })
    assert.deepEqual(plan.errors, []); assert.deepEqual(plan.changedFiles, [])
    assert.equal(plan.maintenance.pending.length, 0)
    const r = spawnSync(process.execPath, [path.resolve(__dirname, '../../skills/gen-project-docs/gen-docs.cjs'), '--stale'], { cwd: root, encoding: 'utf8' })
    assert.equal(JSON.parse(r.stdout).stale, false, r.stdout)
  })
  test('Source edits require review; ordinary intermediate commits remain possible', () => {
    put('src/order.js', 'export const cancelMinutes = 15\n')
    assert(kb.check(root).passed)
    const r = kb.check(root, { strict: true }); assert(!r.passed)
    assert(r.pending.some(p => p.files.includes('src/order.js')))
    const plan = require('../../skills/kb-update/kb-update.cjs').collectUpdate(root, { refresh: false })
    assert.deepEqual(plan.changedFiles, ['src/order.js'])
  })
  test('Partially staged source cannot borrow a receipt for unstaged changes', () => {
    put('.docs/llm-knowledge/business/order/overview.md', '# Order\nCancel within 15 minutes.\n')
    record('domain:order')
    git('add', '.docs')
    const r = kb.check(root, { mode: 'staged', strict: true })
    assert(!r.passed); assert(r.pending.some(p => p.files.includes('src/order.js')))
    git('add', 'src/order.js'); assert(kb.check(root, { mode: 'staged', strict: true }).passed)
    git('commit', '-qm', 'order policy')
  })
  const a = git('rev-parse', 'HEAD')
  test('A different branch uses its own tracked knowledge', () => {
    git('checkout', '-qb', 'feature/user', base)
    put('src/user.js', 'export const enabled = false\n')
    put('.docs/llm-knowledge/business/user/overview.md', '# User\nDisabled.\n')
    record('domain:user'); git('add', '.'); git('commit', '-qm', 'user policy')
    assert(kb.check(root, { mode: 'HEAD', base, strict: true }).passed)
    git('merge', '--no-edit', a)
    assert(kb.check(root, { mode: 'HEAD', base, strict: true }).passed)
  })
  test('An added consumer document with a stale shared-source receipt fails after merge', () => {
    const sharedBase = git('rev-parse', 'HEAD')
    git('checkout', '-qb', 'feature/consumer', base)
    put('.docs/llm-knowledge/business/user/cancellation.md', '# Cancellation UI\n30 minute window.\n')
    kb.record(root, { scope: 'domain:user', status: 'updated', reason: 'Verified cancellation dependency', specReview: 'aligned', sources: ['src/order.js'] })
    git('add', '.'); git('commit', '-qm', 'consumer')
    // Merge A (order change) only: no same-file conflict in the user docs/state.
    git('merge', '--no-edit', a)
    const r = kb.check(root, { mode: 'HEAD', base: a, strict: true })
    assert(!r.passed); assert(r.pending.some(p => p.scope === 'domain:user' && p.files.includes('src/order.js')))
    put('.docs/llm-knowledge/business/user/cancellation.md', '# Cancellation UI\n15 minute window.\n')
    record('domain:user'); git('add', '.')
    assert(kb.check(root, { mode: 'staged', base: a, strict: true }).passed)
    git('commit', '-qm', 'reconcile consumer')
    assert(sharedBase)
  })
  test('Git hook blocks invalid staged metadata even without the plugin', () => {
    put('.docs/llm-knowledge/business/order/overview.md', '# Order\n<<<<<<< ours\n')
    git('add', '.docs')
    const r = spawnSync('git', ['commit', '-qm', 'invalid'], { cwd: root, encoding: 'utf8' })
    assert.notEqual(r.status, 0); assert((r.stdout + r.stderr).includes('conflict_marker'))
    git('restore', '--staged', '.docs'); git('restore', '.docs')
  })
  test('Deleted or changed docs and dangling links require repair', () => {
    put('.docs/llm-knowledge/business/order/overview.md', '# Order\n[Missing](missing.md)\n')
    const r = kb.check(root)
    assert(!r.passed); assert(r.errors.some(e => e.code === 'broken_link'))
    git('restore', '.docs')
  })
  test('Valid Markdown setext headings and YAML reference lists are not conflicts', () => {
    put('.docs/llm-knowledge/business/order/overview.md', 'Order\n=======\nCancellation rules.\n')
    put('.docs/llm-knowledge/business/order/examples.yaml', '- first\n- second\n')
    assert(kb.check(root).passed)
    git('restore', '.docs')
    fs.unlinkSync(path.join(root, '.docs/llm-knowledge/business/order/examples.yaml'))
  })
  test('Deferred decisions are explicit and obey project policy', () => {
    kb.record(root, { scope: 'domain:order', status: 'deferred', reason: 'Owner review pending', specReview: 'deferred' })
    assert(!kb.check(root, { strict: true }).passed)
    put(kb.CONFIG, '{"version":1,"allow_deferred":true}\n')
    const r = kb.check(root, { strict: true }); assert(r.passed); assert(r.warnings.some(w => w.includes('deferred')))
    record('domain:order'); git('restore', kb.CONFIG)
  })
  test('Scope mapping changes invalidate existing receipts', () => {
    put('.docs/llm-knowledge/.profile.yaml', 'project_type: frontend\nsource_root: src\n')
    assert(!kb.check(root, { strict: true }).passed)
    fs.unlinkSync(path.join(root, '.docs/llm-knowledge/.profile.yaml'))
  })
  test('Deleted sources remain pending until explicitly reviewed', () => {
    fs.unlinkSync(path.join(root, 'src/order.js'))
    assert(kb.check(root, { strict: true }).pending.some(p => p.files.includes('src/order.js')))
    git('restore', 'src/order.js')
  })
  test('An unrelated new source is not silently omitted from merge checks', () => {
    put('src/new.js', 'export const added = true\n')
    assert(kb.check(root, { strict: true }).pending.some(p => p.scope === 'common' && p.files.includes('src/new.js')))
    fs.unlinkSync(path.join(root, 'src/new.js'))
  })
  test('Queries do not reuse symbols from another branch revision', () => {
    put('.docs/llm-knowledge/frontend-index.json', JSON.stringify({ git_hash: base, files: [{ path: 'src/order.js', symbols: [{ name: 'OldOnlySymbol' }] }] }))
    const r = spawnSync(process.execPath, [path.resolve(__dirname, '../../skills/kb-query/kb-query.cjs'), 'OldOnlySymbol'], { cwd: root, encoding: 'utf8' })
    const result = JSON.parse(r.stdout)
    assert.equal(result.total, 0); assert(result.warnings.some(w => w.includes('unverified revision')))
  })
  test('Concurrent record cannot overwrite the current writer', () => {
    put('.git/fsflow-kb-maintenance.lock', 'another writer')
    assert.throws(() => record('domain:order'), /EEXIST/)
    fs.unlinkSync(path.join(root, '.git/fsflow-kb-maintenance.lock'))
  })
  test('Deleting the entire KB cannot downgrade merged-result validation', () => {
    git('add', '.'); git('commit', '--allow-empty', '-qm', 'receipts')
    const before = git('rev-parse', 'HEAD')
    git('rm', '-qr', '.docs/llm-knowledge')
    assert(!kb.check(root, { mode: 'staged', base: before, strict: true }).passed)
    git('restore', '--staged', '.docs'); git('restore', '.docs')
  })
  test('Installed CLI runs in an ESM host project without the plugin directory', () => {
    put('package.json', '{"type":"module"}\n')
    const command = path.join(root, '.docs/llm-knowledge/tools/fsflow-kb/commands/kb-maintenance.js')
    const r = spawnSync(process.execPath, [command, 'check', '--ref', 'HEAD', '--strict'], { cwd: root, encoding: 'utf8' })
    assert.equal(r.status, 0, r.stdout + r.stderr)
    fs.unlinkSync(path.join(root, 'package.json'))
  })
  test('Hook uninstall restores prior hook and install does not overwrite a manager', () => {
    cli.uninstallHook(root)
    git('config', '--unset', 'core.hooksPath')
    put('.git/hooks/pre-commit', '#!/bin/sh\nexit 0\n'); fs.chmodSync(path.join(root, '.git/hooks/pre-commit'), 0o755)
    cli.install(root, true); cli.uninstallHook(root)
    assert.equal(fs.readFileSync(path.join(root, '.git/hooks/pre-commit'), 'utf8'), '#!/bin/sh\nexit 0\n')
    git('config', 'core.hooksPath', '.husky')
    put('.husky/pre-commit', '#!/bin/sh\nexit 0\n')
    assert.throws(() => cli.install(root, true), /Existing hook manager/)
  })
  console.log(`Passed ${total} knowledge maintenance tests`)
} finally { fs.rmSync(root, { recursive: true, force: true }) }
